### PR TITLE
Added intro content

### PR DESCRIPTION
**Pull request by TheVedangMishra**
This PR introduces the `IntroductionPage` component for the AICTE Online Meeting System. It enhances the project's introduction page with descriptive content and utilizes Tailwind CSS for styling. The key updates include:

- Added a detailed project description.
- Highlighted the project's features.
- Styled the page using Tailwind CSS for improved visual appeal.

### CODE REVIEW

**Comment by Vaib215** [comment]
Fix this
```
27:63  Error: `'` can be escaped with `&apos;`, `&lsquo;`, `&#39;`, `&rsquo;`.  react/no-unescaped-entities
```

**Comment by TheVedangMishra** [comment]
sure

**Comment by Vaib215** [comment]
ok merging

**Comment by Vaib215** [comment]
Do fix the styling
image

**Pull request merged**
